services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://host.docker.internal:29092,OUTSIDE://host.docker.internal:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr host.docker.internal:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
  console:
    image: docker.redpanda.com/vectorized/console:latest
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_BROKERS: redpanda:9092
      KAFKA_SCHEMAREGISTRY_ENABLED: 1
      KAFKA_SCHEMAREGISTRY_URLS: http://redpanda:8081
      REDPANDA_ADMINAPI_ENABLED: 1
      REDPANDA_ADMINAPI_URLS: http://redpanda:9644
    ports:
      - 18080:8080
    links:
      - redpanda
